// cSpell:locale en,ca

:toc:
:tabsize: 4
:icons: font
:source-highlighter: prettify
:project_id: gs-accessing-data-jpa

This guide walks you through the process of building an application that uses Spring Data JPA to store and retrieve data in a relational database.

== What You Will Build

You will build an application that stores `Customer` POJOs (Plain Old Java Objects) in a memory-based database.

== What You need

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/how_to_complete_this_guide.adoc[]

[[scratch]]
== Starting with Spring Initializr

You can use this https://start.spring.io/#!type=maven-project&language=java&platformVersion=3.1.5&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=accessing-data-jpa&name=accessing-data-jpa&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.accessing-data-jpa&dependencies=data-jpa,h2[pre-initialized project] and click Generate to download a ZIP file. This project is configured to fit the examples in this tutorial.

To manually initialize the project:

. Navigate to https://start.spring.io.
This service pulls in all the dependencies you need for an application and does most of the setup for you.
. Choose either Gradle or Maven and the language you want to use. This guide assumes that you chose Java.
. Click *Dependencies* and select *Spring Data JPA* and then *H2 Database*.
. Click *Generate*.
. Download the resulting ZIP file, which is an archive of a web application that is configured with your choices.

NOTE: If your IDE has the Spring Initializr integration, you can complete this process from your IDE.

NOTE: You can also fork the project from Github and open it in your IDE or other editor.

[[initial]]
== Define a Simple Entity

In this example, you store `Customer` objects, each annotated as a JPA entity. The
following listing shows the Customer class (in
	`src/main/java/com/example/accessingdatajpa/Customer.java`):

====
[source,java,tabsize=2,indent=0]
----
include::complete/src/main/java/com/example/accessingdatajpa/Customer.java[]
----
====

Here you have a `Customer` class with three attributes: `id`, `firstName`, and `lastName`.
You also have two constructors. The default constructor exists only for the sake of JPA.
You do not use it directly, so it is designated as `protected`. The other constructor is
the one you use to create instances of `Customer` to be saved to the database.

The `Customer` class is annotated with `@Entity`, indicating that it is a JPA entity.
(Because no `@Table` annotation exists, it is assumed that this entity is mapped to a
	table named `Customer`.)

The `Customer` object's `id` property is annotated with `@Id` so that JPA recognizes it as
the object's ID. The `id` property is also annotated with `@GeneratedValue` to indicate
that the ID should be generated automatically.

The other two properties, `firstName` and `lastName`, are left unannotated. It is assumed
that they are mapped to columns that share the same names as the properties themselves.

The convenient `toString()` method print outs the customer's properties.

== Create Simple Queries

Spring Data JPA focuses on using JPA to store data in a relational database. Its most
compelling feature is the ability to create repository implementations automatically, at
runtime, from a repository interface.

To see how this works, create a repository interface that works with `Customer` entities
as the following listing (in `src/main/java/com/example/accessingdatajpa/CustomerRepository.java`) shows:

====
[source,java,tabsize=2]
----
include::complete/src/main/java/com/example/accessingdatajpa/CustomerRepository.java[]
----
====

`CustomerRepository` extends the `CrudRepository` interface. The type of entity and ID
that it works with, `Customer` and `Long`, are specified in the generic parameters on
`CrudRepository`. By extending `CrudRepository`, `CustomerRepository` inherits several
methods for working with `Customer` persistence, including methods for saving, deleting,
and finding `Customer` entities.

Spring Data JPA also lets you define other query methods by declaring their method
signature. For example, `CustomerRepository` includes the `findByLastName()` method.

In a typical Java application, you might expect to write a class that implements
`CustomerRepository`. However, that is what makes Spring Data JPA so powerful: You need
not write an implementation of the repository interface. Spring Data JPA creates an
implementation when you run the application.

Now you can wire up this example and see what it looks like!

== Create an Application Class

Spring Initializr creates a simple class for the application. The following listing shows
the class that Initializr created for this example (in
`src/main/java/com/example/accessingdatajpa/AccessingDataJpaApplication.java`):

====
[source,java,tabsize=2]
----
include::initial/src/main/java/com/example/accessingdatajpa/AccessingDataJpaApplication.java[]
----
====

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/spring-boot-application-new-path.adoc[]

Now you need to modify the simple class that the Initializr created for you. To get output
(to the console, in this example), you need to set up a logger. Then you need to set up
some data and use it to generate output. The following listing shows the finished
`AccessingDataJpaApplication` class (in
`src/main/java/com/example/accessingdatajpa/AccessingDataJpaApplication.java`):

====
[source,java,tabsize=2]
----
include::complete/src/main/java/com/example/accessingdatajpa/AccessingDataJpaApplication.java[]
----
====

The `AccessingDataJpaApplication` class includes a `demo()` method that puts the `CustomerRepository` through a few tests. First, it fetches the `CustomerRepository` from the Spring application context. Then it saves a handful of `Customer` objects, demonstrating the `save()` method and setting up some data to work with. Next, it calls `findAll()` to fetch all `Customer` objects from the database. Then it calls `findById()` to fetch a single `Customer` by its ID. Finally, it calls `findByLastName()` to find all customers whose last name is "Bauer". The `demo()` method returns a `CommandLineRunner` bean that automatically runs the code when the application launches.

NOTE: By default, Spring Boot enables JPA repository support and looks in the package (and
	its subpackages) where `@SpringBootApplication` is located. If your configuration has
	JPA repository interface definitions located in a package that is not visible, you can
	point out alternate packages by using `@EnableJpaRepositories` and its type-safe
	`basePackageClasses=MyRepository.class` parameter.

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/build_an_executable_jar_mainhead.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/build_an_executable_jar_with_both.adoc[]

When you run your application, you should see output similar to the following:

====
----
== Customers found with findAll():
Customer[id=1, firstName='Jack', lastName='Bauer']
Customer[id=2, firstName='Chloe', lastName='O'Brian']
Customer[id=3, firstName='Kim', lastName='Bauer']
Customer[id=4, firstName='David', lastName='Palmer']
Customer[id=5, firstName='Michelle', lastName='Dessler']

== Customer found with findById(1L):
Customer[id=1, firstName='Jack', lastName='Bauer']

== Customer found with findByLastName('Bauer'):
Customer[id=1, firstName='Jack', lastName='Bauer']
Customer[id=3, firstName='Kim', lastName='Bauer']
----
====

== Summary

Congratulations! You have written a simple application that uses Spring Data JPA to save
objects to and fetch them from a database, all without writing a concrete repository
implementation.

NOTE: If you want to expose JPA repositories with a hypermedia-based RESTful front end
with little effort, you might want to read link:/guides/gs/accessing-data-rest[Accessing JPA Data with REST].

== See Also

The following guides may also be helpful:

* https://spring.io/guides/gs/accessing-data-rest[Accessing JPA Data with REST]
* https://spring.io/guides/gs/accessing-data-gemfire/[Accessing Data with Gemfire]
* https://spring.io/guides/gs/accessing-data-mongodb/[Accessing Data with MongoDB]
* https://spring.io/guides/gs/accessing-data-mysql/[Accessing data with MySQL]
* https://spring.io/guides/gs/accessing-data-neo4j/[Accessing Data with Neo4j]


== AAS extension

Per tal d'aprofundir una mica més en la persistència de dades emprant JPA,
s'ha estès una mica més el tutorial, per tal d'incloure relacions entre diferents entitats.

== Relació _one-to-many_

Per tal de modelar una relació _one-to-many_ es definirà l'entitat `Order`,
que representa una comanda d'un client.

Un `Customer` pot tenir moltes `Order`, però una `Order` pertany a un sol `Customer`.
Per tant, es tracta d'una relació _one-to-many_.

Recorda que en bases de dades relacionals, una relació _one-to-many_,
en realitat, es controla des de el costat del _many_, mitjançant una clau forana cap al costat del _one_.
Cal tenir això en compte a l'hora de definir les entitats relacionades.

En primer lloc, defineix l'entitat `Order`:

[source, java]
----
@Entity
@Table(name = "orders")
public class Order {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Long id;

	@ManyToOne
	@JoinColumn(
			name = "customer_id",
			nullable = false )
	private Customer customer;

	private BigDecimal amount;

	protected Order() {}

	public Order(BigDecimal amount) {
		this.amount = amount;
	}

	// Getters and setters

}
----

L'anotació `@ManyToOne` indica que la propietat anotada fa referència a una altra entitat.
L'anotació opcional `@JoinColumn` permet ajustar la configuració de la relació.
En aquest cas se li especifica el nom del camp de la taula `orders` que farà referència a la taula de clients.
A més, també s'especifica que aquest camp no pot ser `null`.

A l'altra costat de la relació, al costat del client, es pot definir una propietat inversa,
per tal de poder navegar la relació en ambdós sentits:


[source, java]
----
public class Customer {
	
	// ...

	@OneToMany(mappedBy = "customer")
	private Set<Order> orders = new HashSet<>();

	// ...

	public void addOrder(Order order) {
		order.setCustomer(this);
		this.orders.add(order);
	}

	public void removeOrder(Order order) {
		order.setCustomer(null);
		this.orders.remove(order);
	}

}
----

L'anotació `OneToMany` indica que la propietat anotada fa referència al costat _many_ d'una relació _one-to-many_.
En aquest cas, s'ha d'indicar l'atribut `mappedBy`, que indica el camp de l'entitat `Order` que fa referència a l'entitat `Customer`,
per tal de que la implementació de JPA pugui establir la relació correctament.

Note: Fixa't que el nom del camp es refereix al nom del camp en la classe Java,
no al nom del camp en la taula de la base de dades.

Per tal de poder consultar comandes, cal definir el corresponent repository:

[source, java]
----
public interface OrderRepository extends CrudRepository<Order, Long> {

	List<Order> findByCustomer(Customer customer);

	Order findOneById(long id);

}
----

En aquest repositori s'ha definit un mètode per tal d'obtenir totes les comandes associades a un client.
Fixa't que quan es treballa amb JPA, no es treballa amb els identificadors de les entitats.
Una vegada configurada la relació, JPA ja sap com obtenir les entitats relacionades i,
per tant, es treballa directament amb els objectes Java, com pots veure en el mètode `findByCustomer`.

Per tal de fer més fàcil la gestió de les entitats, és habitual configurar _cascades_ a les relacions,
per tal de propagar les operacions d'escriptura des de l'entitat principal, cap a l'entitat secundària.

En aquest cas, l'entitat principal és el client, i la secundària són les seves comandes.
Per tant, defineix la següent cascada a l'entitat `Customer`:

[source, java]
----
	@OneToMany(
			mappedBy = "customer",
			cascade = { CascadeType.MERGE, CascadeType.PERSIST }
	)
	private Set<Order> orders = new HashSet<>();
----

Amb aquesta cascada, li indiquem a la implementació de JPA que quan es persisteixi
una entitat de tipus `Customer`, també ha de persistir les entitats de tipus `Order` relacionades.

Ara, hauries de poder executar la següent prova unitaria:

[source, java]
----
@DataJpaTest
public class OneToManyTests {

    @Autowired
    private TestEntityManager entityManager;

    @Autowired
    private CustomerRepository customers;

    @Autowired
    private OrderRepository orders;


    @Test
    public void testFindOrderByCustomer() {
        Customer customer = new Customer("first", "last");
        Order order = new Order(new BigDecimal("15.75"));
        customer.addOrder(order);
        customer = customers.save(customer);

        List<Order> foundOrders = orders.findByCustomer(customer);

        assertThat(foundOrders).hasSize(1);
        assertThat(foundOrders.get(0).getAmount()).isEqualTo(new BigDecimal("15.75"));
    }
}
----

Fixa't que la única operació `save` que s'executa és la del client.
Però com que has definit una cascada, en persistir el client també es persisteix la comanda.
Per tant, quan després es busca la comanda emprant el repositori de comandes, es troba la comanda.

Com que no té sentit que hi hagi comandes sense client, té sentit definir també una cascada d'esborrat,
de forma que si s'esborra un client també s'esborrin les seves comandes.

A més, tampoc té sentit que hi hagi ordres que no estiguin associades a clients,
això, de fet, no ho permetria la base de dades, ja que hem definit que la columna `customer_id`
no pot ser tenir valor `null`.

Modifica la relació a l'entitat `Customer`:

[source, java]
----
	@OneToMany(
			mappedBy = "customer",
			cascade = { CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REMOVE },
			orphanRemoval = true
	)
	private Set<Order> orders = new HashSet<>();
----

Fixa't que hem afegit `CascadeType.REMOVE` a la cascada del client cap a la comanda.
Això provocarà que quan s'esborri un client, també s'esborrin les comandes associades.

També hem afegit el camp `orphanRemoval = true`.
Això provoca que si en algun moment una comanda es queda sense un client associat,
s'esborri automàticament.

Ara hauries de poder executar les següents proves unitàries:

[source, java]
----
@DataJpaTest
public class OneToManyTests {

	// ...

	 @Test
    public void testOrphanRemovalAll() {
        Customer customer = new Customer("first", "last");
        Order order = new Order(new BigDecimal("15.75"));
        customer.addOrder(order);
        customer = customers.save(customer);

        customer.getOrders().clear();
        customers.save(customer);

        List<Order> foundOrder = orders.findByCustomer(customer);
        assertThat(foundOrder).hasSize(0);
    }

    @Test
    public void testOrphanRemovalOne() {
        Customer customer = new Customer("first", "last");
        Order order1 = new Order(new BigDecimal("15.75"));
        Order order2 = new Order(new BigDecimal("45.22"));
        customer.addOrder(order1);
        customer.addOrder(order2);
        customer = customers.save(customer);

        customer.removeOrder(customer.getOrders().stream().findFirst().orElseThrow());
        customers.save(customer);

        List<Order> foundOrder = orders.findByCustomer(customer);
        assertThat(foundOrder).hasSize(1);
    }

	@Test
    public void testDeleteCascade() {
        Customer customer = new Customer("first", "last");
        Order order = new Order(new BigDecimal("15.75"));
        customer.addOrder(order);
        customer = customers.save(customer);

        customers.delete(customer);

        Iterable<Order> foundOrders = orders.findAll();
        assertThat(StreamSupport.stream(foundOrders.spliterator(), false).count()).isEqualTo(0);
    }

}
----

Fixa't que en el primer cas s'elimina la relació entre el client i totes les seves comandes.
Quan es persisteix el client, es propaga la operació de persistència (degut a la cascada)
i com que la implementació de JPA detecta que les comandes han quedat "orfes", les elimina.

En el segon cas, només s'elimina la relació entre el client i una de les seves comandes associades.
Per tant, quan després es consulten les comandes associades al client, només se'n troba una.

Finalment, en el tercer cas s'elimina el client.
En conseqüència, quan després s'obtenen totes les comandes, no se'n troba cap.

== Relació _many-to-many_

JPA suporta la definició de relacions _many-to-many_.
En aquest cas, el que fa la implementació de JPA és crear una taula associativa.

Modifica la classe `Customer`, i afegeix-li la següent relació _many-to-many_:


[source, java]
----
 public class Customer {

	// ...

	@ManyToMany
	private Set<Customer> friends = new HashSet<>();

	// ...

	public void addFriend(Customer customer) {
		this.friends.add(customer);
	}

	public void removeFriend(Customer customer) {
		this.friends.remove(customer);
	}

 }
----

D'aquesta forma s'indica que l'entitat client té una relació _many-to-many_ amb ella mateixa.

A continuació, defineix el següent mètode al `CustomerRepository`:

[source, java]
----
public interface CustomerRepository extends CrudRepository<Customer, Long> {

	// ...

	List<Customer> findByFriendsContains(Customer friend);

}
----

Ara, hauries de poder executar aquestes proves unitàries:

[source, java]
----
@DataJpaTest
public class ManyToManyTests {

    @Autowired
    private CustomerRepository customers;

    @Test
    public void testFindCustomerByFriends() {
        customers.saveAll(List.of(
                new Customer("first1", "last1"),
                new Customer("first2", "last2"),
                new Customer("first3", "last3")
        ));

        Customer customer1 = customers.findByLastName("last1").get(0);
        Customer customer3 = customers.findByLastName("last3").get(0);
        customer1.addFriend(customer3);
        customers.save(customer1);

        List<Customer> friendsOf3 = customers.findByFriendsContains(customer3);
        assertThat(friendsOf3).extracting(Customer::getLastName).containsOnly("last1");

        List<Customer> friendsOf1 = customers.findByFriendsContains(customer1);
        assertThat(friendsOf1).isEmpty();
    }

    @Test
    public void testFindCustomerByReciprocalFriends() {
        customers.saveAll(List.of(
                new Customer("first1", "last1"),
                new Customer("first2", "last2"),
                new Customer("first3", "last3")
        ));

        Customer customer1 = customers.findByLastName("last1").get(0);
        Customer customer3 = customers.findByLastName("last3").get(0);
        customer1.addFriend(customer3);
        customer3.addFriend(customer1);
        customers.save(customer1);
        customers.save(customer3);

        List<Customer> friendsOf1 = customers.findByFriendsContains(customer1);
        assertThat(friendsOf1).extracting(Customer::getLastName).containsOnly("last3");

        List<Customer> friendsOf3 = customers.findByFriendsContains(customer3);
        assertThat(friendsOf3).extracting(Customer::getLastName).containsOnly("last1");
    }

}
----

En aquest cas particular, els dos participants de la relació fan referència a la mateixa entitat,
però això no té perquè ser així, evidentment.
Fixa't que, tot i que les dues entitats són de la mateixa classe, l'ordre importa.
És a dir, que `customer1` tingui com amic a `customer3`, no implica que `customer3` tingui com a amic a `customer1`.

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/footer.adoc[]

